### ISSUE TITLE
Collate and document backup strategy for our infrastructure machines

### ISSUE THREAD

**Issue by sxa** [adoptium/infrastructure#1295]
The top level README.md on the infrastructure repository is somewhat out of date with respect to our backup setups and policy for the infrastructure systems (jenkins, api, blog, monitoring etc.)

We should get the documentation up to date, while ensuring that all appropriate backups are definitely in place and running.

**Comment by sxa** [comment]
@gdams @karianna Can we work on this please? I need to know what we currently have in place for backups on our infrastructure systems as I'm not confident that our current documentation is up to date

**Comment by sxa** [comment]
@gdams @karianna On the TSC call it was mentioned that we do still have these backups in place - can we have a discussion and get the current situation correctly documented please?

**Comment by sxa** [comment]
@gdams When we discussed this you wre going to set up some EC2 space for this - was it done?

**Comment by sxa** [comment]
@gdams @karianna I'm guessing we're not lilkely to choose EC2 for this now?

We have backups of the Bastillion host now, but in general the requirements are quite small here I believe. We have bastillion, nagios, keybox and jenkins as the main servers under consiideration here I believe. Most of these just need the configuration backed up to a location off the machine. Another option would be to choose one server (like the bastillion one which is already backed up) and just back up all the others onto there.

Bastillion was recently tested as we moved it off godaddy, but we should get things in place and then verify each of them (Including jenkins) in terms of being able to restore them. We should also consider whether we want to backup the historya nd artefacts of all jobs (my gut feel is no, but perhaps we should have a process to restore them from github if required)

**Comment by aahlenst** [comment]
I don't think that the sponsorship status of a service should influence the selection of a service, especially if it's as important as backup. We should select the best service for our needs and then pay for it. Everything else is unsustainable. Imagine having to switch the backup solution every year because a sponsorship runs out.

Doing backups over the internet is painful:

* It's slow, especially if you're waiting for a restore.
* It's expensive (you have to pay ingress and egress at most locations).

All core services need proper full backups so that we can restore a system from a backup. Everything else is brittle and you don't want this in a high stress situation. The core services are:

* TRSS (some GB?)
* Jenkins (single digit TB)
* Nagios (some GB)
* Bastillion (some GB)
* AWX (some GB)
* Keybox (some GB)
* Download server (not operational yet, single digit TB)
* API (some GB)

Did I miss something?

For a consistent backup, we need a volume manager that can do block level snapshots of volumes. So either we need LVM or OpenZFS everywhere or we delegate that job.

That most of the systems are at different providers is a hurdle because it either forces us to do backups over the internet or we need multiple backup infrastructures. Both isn't ideal. Because we need multiple new systems for Adoptium, this would be a good opportunity to consolidate the critical systems in one or two places. This would also make operations easier because you don't need to know the quirks of half a dozen setups.

What I personally find very attractive is to select one of the big clouds (AWS, Azure) for the core services: They offer snapshot-based backups with offsite storage as a managed service. Although they aren't exactly cheap like Hetzner, I think it's worth it because we save on human resources, we get top security and reliability, complexity is significantly reduced. Those services are battle tested. Whatever we deploy isn't.

**Comment by sxa** [comment]
At the moment almost all of those services are hosted on different providers which makes a consistent "battle tested" solution hard just now without moving things (which probably isn't too hard), but I would agree with your sentiments and backup is certainly not something we should be skimping on (and we do at the moment...)

**Comment by sxa** [comment]
Initialy "better than nothing" backups being created on the bastillion host for bastillion, jenkins and nagios (so far!) as the `backups` user. TRSS needs to be added too once dataset to backup is defined.

**Comment by sxa** [comment]
Updated status of this:
- Added backup of the `userContent` directory on jenkins via rsync
- Set up cron job
- Initial TRSS backups in place using mongodump (based on the work in https://github.com/AdoptOpenJDK/openjdk-test-tools/pull/345)

**Comment by sxa** [comment]
Still need to do AWX

**Comment by sxa** [comment]
AWX not yet included but it can be recreated from scratch as the history is not critical. Next stage is to attempt to validate that the backups work (i.e. can be recovered)

**Comment by karianna** [comment]
https://github.com/AdoptOpenJDK/openjdk-infrastructure/pull/2077 as one small doc update.  @Willsparker could you update that Backup table with the Nagios and AWX recovery steps after this lands?

**Comment by Willsparker** [comment]
I can certainly do Nagios. @sxa setup AWX so I'm not sure on how it's currently backed-up / recovered :)

**Comment by sxa** [comment]
Honestly, AWX takes less than an hour to recreate from scratch from [the instructions](https://github.com/AdoptOpenJDK/openjdk-infrastructure/wiki/Ansible-AWX#setting-up-the-configuration) so if we lost it I'd just create it from those. I don't think there's enough transient data for it to reall be worth backing up/restoring unlike most of our other servers, but if someone decided to do it I won't object obviously - there was some suggestions on backups at the end of the doc ;-)

**Comment by sxa** [comment]
Probably superceded by something in SSDF, but bumping for now.

**Comment by sxa** [comment]
Current status:
Cron job running on bastillion which creates and stores tarballs of the setups and data where practical as follows:

Product | Size/day | What is backed up
--- | --- | ---
bastillion | 21Mb | Full product backup with database
nagios | 140Mb | Entire /usr/local/nagios (Now excludes `nagiosgraph.log` and `archives`)
TRSS | 650Mb | Mongodump of database
jenkins | ~16Mb | config.xmls, plus text file with plugin list

NOTE: nagios was 600Mb prior to today's `nagiosgraph.log` and `archives` exclusions. Similarly jenkins backups reduced from 100Mb to ~16Mb by removing `config-history`

Jenkins was also backing up the `thinbackup` files, but is no longer doing so as they are not in the expected location. This needs to be fixed.

There is also a single backup of the `userContent` updated using rsync each day, although that currently amounts to 40Gb

This will store recent backups on a daily basis and the backup on the first of the month will never be deleted.

**Comment by sxa** [comment]
The [VagrantPlaybookCheck](https://ci.adoptium.net/view/Tooling/job/VagrantPlaybookCheck/) job was not discarding old runs. I've now updated that.

The backups of that were accounting for most of the space on the thinbackup file system (417,665Kb out of 430,139Kb). Have stored `VagrantPlaybookCheck-preDONOTKEEP.tar.xz` on the backup server for now in case they're needed and implemented discarding.

**Comment by sxa** [comment]
Subject to the PR being merged this work is complete.
