### ISSUE TITLE
jdk15 pLinux cloud nodes not setting boot jdk correctly?

### ISSUE THREAD

**Issue by andrew-m-leonard** [adoptium/infrastructure#1707]
https://ci.adoptopenjdk.net/view/Failing%20Builds/job/build-scripts/job/jobs/job/jdk15u/job/jdk15u-linux-ppc64le-openj9/118/console
```
21:58:02  BUILD_CONFIG[WORKSPACE_DIR]="/home/ubuntu/workspace/build-scripts/jobs/jdk15u/jdk15u-linux-ppc64le-openj9/workspace"
21:58:02  [WARNING] Unable to find java to run gradle with, this build may fail with /bin/java: No such file or directory. Set JAVA_HOME, JDK8_BOOT_DIR or JDK11_BOOT_DIR to squash this warning: 

```

**Comment by sxa** [comment]
In light of https://github.com/AdoptOpenJDK/openjdk-build/pull/2246 it shouldn't be using docker nodes, unless it hit the issue I saw in https://github.com/AdoptOpenJDK/openjdk-build/pull/2246#issuecomment-731246493

**Comment by sxa** [comment]
I'm going to assume that the "real" build nodes were all in use so it couldn't use them and tried to start a new one rather than waiting. Have kicked off https://ci.adoptopenjdk.net/job/build-scripts/job/openjdk15-pipeline/380/ (there are two real executors left so one of the three builds may have the same problem again).

Saying that, there's no reason why it should fail to find a boot JDK that I'm aware of, so if it couldn't find or download a valid boot JDK this is still a valid problem that needs to be resolved.

**Comment by Willsparker** [comment]
As far as I can see, this isn't being run on the docker nodes, it's being run on temporary machines made using this option:
![image](https://user-images.githubusercontent.com/52783864/101478604-d6da6e80-3948-11eb-9069-3b0b2994203e.png)

That being said, I don't know where / if there's any setting up done on those machines before they're tasked to build the JDK- so there very well may not be a JDK on there

**Comment by sxa** [comment]
Those are the docker nodes.

**Comment by Willsparker** [comment]
oh! Do you know if they have any playbook or anything run on them?

**Comment by andrew-m-leonard** [comment]
@sxa and again last night https://ci.adoptopenjdk.net/view/Failing%20Builds/job/build-scripts/job/jobs/job/jdk16/job/jdk16-linux-ppc64le-openj9/21/

**Comment by sxa** [comment]
I'm going to close this since the builds have not been running on the dynamically provisioned machines and this problem has not shown up for a while as far as I'm aware. If you disagree feel free to re-open @andrew-m-leonard
