### ISSUE TITLE
test-macincloud-macos1010-x64-2 seems to be missing net/sf/antcontrib/antlib.xml

### ISSUE THREAD

**Issue by andrew-m-leonard** [adoptium/infrastructure#1922]
https://ci.adoptopenjdk.net/computer/test-macincloud-macos1010-x64-2/
```
07:57:36  Buildfile: /Users/jenkins/workspace/Grinder/openjdk-tests/TKG/scripts/build_test.xml
07:57:37    [taskdef] Could not load definitions from resource net/sf/antcontrib/antlib.xml. It could not be found.
07:57:37    [taskdef] Could not load definitions from resource net/sf/antcontrib/antlib.xml. It could not be found.
```
https://ci.adoptopenjdk.net/job/Grinder/6725/console

**Comment by sxa** [comment]
Looks from the slack thread as though George is investigating so we should hold off on this for now (I'd rather not have two people experimenting on the machine at the same time!)

**Comment by andrew-m-leonard** [comment]
Disabled ci.test.role on this node: https://ci.adoptopenjdk.net/computer/test-macincloud-macos1010-x64-2/

**Comment by andrew-m-leonard** [comment]
Running Grinder to check node now good: https://ci.adoptopenjdk.net/job/Grinder/374/

**Comment by andrew-m-leonard** [comment]
I can confirm the node still does not have the correct ant-contrib setup:
https://ci.adoptopenjdk.net/view/Test_grinder/job/Grinder/380/console
```
15:06:16    [taskdef] Could not load definitions from resource net/sf/antcontrib/antlib.xml. It could not be found.
```
@gdams fyi

**Comment by sxa** [comment]
Note: This machine is currently offline - I am in contact with MacInCloud to resolve this, although it will probably be superceded by whatever happs with #2476

**Comment by sxa** [comment]
Right ...
- Both machines have `/usr/bin/ant` symlinked to `/usr/local/opt/apache-ant-1.10.1/bin/ant`
It's not entirely clear why that isn't adequate, since the `ant-1.10.1` directory also contains `lib/ant-contrib.jar` on both systems.

However we typically use ant 1.10.5. This is installed on both machines. I've added `lib/ant-contrib.jar` into that install and symlinked `bin/ant` from that install to `/usr/local/bin/ant` which should allow that version to be picked up properly now.

I've run smoke tests on each of the two machines to verify this, so I have now re-enabled them in jenkins for now, although as per the PR mentioned above this comment, the machines are going to be replaced soon.
