### ISSUE TITLE
New openjdk test case dependencies - hostname and which

### ISSUE THREAD

**Issue by lumpfish** [adoptium/infrastructure#2175]
jdk17 openjdk tests have introduced a dependency on `hostname` and `which`, which are missing from some test machines.

So far the failures I've seen have been on docker machines:
```
test-docker-fedora33-armv8l-2
test-docker-fedora33-x64-3
```
Affected test cases:
TEST: sun/net/www/protocol/https/HttpsURLConnection/PostThruProxyWithAuth.java (needs `hostname`)
TEST: java/nio/file/attribute/BasicFileAttributeView/UnixSocketFile.java (needs `which`)

**Comment by sxa** [comment]
This will likely affect all of the `test-docker-fedora` systems. The appropriate packages will need to be added to the [DockerStatic role](https://github.com/AdoptOpenJDK/openjdk-infrastructure/tree/master/ansible/playbooks/AdoptOpenJDK_Unix_Playbook/roles/DockerStatic/Dockerfiles) and then deployed onto all existing ones:

- [ ] test-docker-fedora33-armv8-1
- [ ] test-docker-fedora33-armv8l-2
- [ ] test-docker-fedora33-ppc64le-1
- [ ] test-docker-fedora33-x64-1
- [ ] test-docker-fedora33-x64-2
- [ ] test-docker-fedora33-x64-3

**Comment by sxa** [comment]
For future reference if anyone's rading this:
- Log into host
- docker ps | awk '/f33/{print$NF}'
- For each entry (likely juist `f33_2227` run e.g. `docker exec -it f33_2227 dnf install -y which hostname`

Then, of course, [update the dockerfiles](https://github.com/adoptium/infrastructure/pull/2247) so that new ones get the updates :-)

**Comment by karianna** [comment]
@sxa This was closed because the PR was merged, not sure if you want re-opened until its all applied
