### ISSUE TITLE
Ansible request for reworked timesync role

### ISSUE THREAD

**Issue by Willsparker** [adoptium/infrastructure#2199]
Currently, we have the `NTP_TIME` role, that will effectively disable `systemd-timesyncd` and enable `ntp` for most platforms, however that doesn't reflect the checks that Nagios makes (see reference section). It's been determined that it's probably best we just keep the defaults of the platform, which I _think_ is what the Nagios checks already confirm (i.e NTP for RHEL/CentOS, timesyncd for everything else), so changes to the `NTP_TIME` role will be required.

## Ref:
- Slack conversation : https://adoptium.slack.com/archives/C53GHCXL4/p1622626868016400
- `Nagios_Ansible_Config_Tool`. The platform specific checks section : https://github.com/adoptium/infrastructure/blob/master/ansible/playbooks/Supporting_Scripts/Nagios_Ansible_Config_tool/Nagios_Ansible_Config_tool.sh#L128
- `check_ntp_timesync`, for CentOS and RHEL platforms : https://github.com/adoptium/infrastructure/blob/master/ansible/playbooks/AdoptOpenJDK_Unix_Playbook/roles/Nagios_Plugins/tasks/additional_plugins/check_ntp_timesync 
- `check_timesync`, for Debian/Ubuntu/SLES platforms: https://github.com/adoptium/infrastructure/blob/master/ansible/playbooks/AdoptOpenJDK_Unix_Playbook/roles/Nagios_Plugins/tasks/additional_plugins/check_timesync

**Comment by sxa** [comment]
Implementing this will likely be a better option that explicitly disabling the `timesyncd` daemon so we'd be able to remove https://github.com/adoptium/infrastructure/pull/2219

**Comment by sxa** [comment]
Adding `good first issue` - needs a way to re-enable `timesyncd` as a way of keeping the time on the machines correct.

**Comment by zdtsw** [comment]
I am bit confused for the current implementation, please help me to understand:
1. on rhel8/sles15, we install chronyd than ntp, but the check_ntp_timesync only checks service ntp
does it mean, we are currently getting "warning - check ntpd service" on rhel8/sles15?
2. is the default check "check_ntp_peer" enough to cover all cases(rhel centos ubuntu debian sles freebsd even macos) so we do not really need a customized check_ntp_timesync/check_timesync script?
3. if yes for (2), what we need to do for this issue is to enable enable systemd-timesyncd on existing ubuntu/debian machines

**Comment by sxa** [comment]
@steelhead31 Can you provide input as to whether we need to do any more work here?

**Comment by steelhead31** [comment]
@sxa .. this needs some further work as per @zdtsw concerns...  
  
currently nagios uses both ntp & timesyncd, via the custom check\_ntp\_timesync and check\_timesync scripts which both have exceptions added for various versions of Ubuntu. This is working ok on all of the current machines.  The work remaining to rationalist & standardise these checks is detailed below :   
 

1.  Test if check\_ntp\_peer is O/S independent and will work regardless of time synchronisation process.
2.  If check ntp peer is usable, reconcfigure the host checks to use this command with appropriate parameters  
    OR
3.  If check ntp peer is not suitable, EITHER rationalise the two scripts detailed above, into a single cover all, and maintain future additions OR find a suitable alternative.

I've added this to the EPIC, and will pick it up as part of the ongoing works.

**Comment by steelhead31** [comment]
Having done some investigations, the universal fix is to ensure that timedatectl is synced via NTP.  
  
There is a role in the Unix playbooks that installs NTP, however in order to meet the nagios check, an additional package and a single command to configure is required...  
  
apt install systemd-timesyncd  
timedatectl set-ntp true

**Comment by steelhead31** [comment]
Following the addition of Jenkins to Nagios, we need a version of check\_ntp\_timesync for ubuntu machines, which checks for NTP rather than timesyncd ...

**Comment by steelhead31** [comment]
With the new plugin, and the changes to nagios server configuration templates, to ensure that each host checks the correct default type of time synchronisation, this can now be considered complete.
