### ISSUE TITLE
WIndows playbook fails on codesigncert role

### ISSUE THREAD

**Issue by sxa** [adoptium/infrastructure#2315]
Please put the name of the software product (and affected platforms if relevant) in the title of this issue

- [ ] Missing install
- [x] Bug in ansible playbook
- [ ] Request for new playbook addition

Details:
Possibly introduced by https://github.com/adoptium/infrastructure/pull/2203? It's [failing in VPC](https://ci.adoptopenjdk.net/view/Tooling/job/VagrantPlaybookCheck/1240/OS=Win2012,label=vagrant/console) preventing checks on PRs:
```
15:14:41 
15:14:41 The error appears to be in '/home/vagrant2/workspace/VagrantPlaybookCheck/OS/Win2012/label/vagrant/adoptopenjdkPBTests/AdoptOpenJDK-master/ansible/playbooks/AdoptOpenJDK_Windows_Playbook/roles/CodesignCert/tasks/main.yml': line 9, column 3, but may
15:14:41 be elsewhere in the file depending on the exact syntax problem.
15:14:41 
15:14:41 The offending line appears to be:
15:14:41 
15:14:41 
15:14:41 - name: Remove windows.p12, if present
15:14:41   ^ here
15:14:41 ++ date +%T
15:14:41 + echo The playbook finished at : 09:09:40
```

**Comment by sxa** [comment]
@gdams Can you take  alook at this please?

**Comment by Willsparker** [comment]
Supposedly it doesn't like `ansible.windows.win_file` as a module definition, despite it being [technically correct](https://docs.ansible.com/ansible/latest/collections/ansible/windows/win_file_module.html). This is due to a difference in Ansible version - the latest Ansible (v4, apparently?!), uses that syntax. `2.9.*` uses the old `win_file` syntax, and the VPC machine uses Ansible 2.9.16. 

I've made the changes, and are testing them here: https://ci.adoptopenjdk.net/job/VagrantPlaybookCheck/1339/
