### ISSUE TITLE
Access request for machine labeled with `dockerBuild`

### ISSUE THREAD

**Issue by sophia-guo** [adoptium/infrastructure#2410]
Access level:

- [ ] Non-privileged
- [x] jenkins user
- [x] root/Administrative
- [ ] other (Please specify):

System for which access is needed: 
https://ci.adoptopenjdk.net/computer/docker-packet-ubuntu2004-amd-1/ or
https://ci.adoptopenjdk.net/computer/docker-packet-ubuntu2004-intel-1/ 

Please explain why you need this access including whether it is a temporary or permanent request:
Installer generation run on those machines, get the direct access will help the debug process if there is any unexpected failures.

**Comment by sxa** [comment]
Access granted to `sophia@139.178.85.251` which is [docker-package-ubuntu2004-amd-1](https://ci.adoptopenjdk.net/computer/docker-packet-ubuntu2004-amd-1)

**Comment by sophia-guo** [comment]
Log in `ssh sophia@139.178.85.251` and run gradlew

```
$ ./gradlew --info clean packageJdkRedHat checkJdkRedHat --parallel -PPRODUCT=temurin -PPRODUCT_VERSION=8                           

ERROR: JAVA_HOME is not set and no 'java' command could be found in your PATH.

Please set the JAVA_HOME variable in your environment to match the
location of your Java installation.
```

**Comment by sophia-guo** [comment]
Similar to https://github.com/adoptium/infrastructure/issues/2412 ?

Suppose my access level is 
jenkins user,  root/Administrative

**Comment by sxa** [comment]
Since those machines have traditionally been used only for running things in docker containers they're not set up to run many other operations by default, but if you're at the comment line you can always `export JAVA_HOME=/usr/lib/jvm/jdk-11` but I'll make a change so that `/usr/bin/java` and `/usr/bin/javac` points to the right version. Do the jenkins packaging jobs work ok on that machine? It's unlikely that `JAVA_HOME` is set via jenkins either on that machine :-)

**Comment by sophia-guo** [comment]
Thanks @sxa That works!

Jenkins packaging works without setting JAVA_HOME, which explicitly install jdk11 by jenkins tools step.
