### ISSUE TITLE
System unavailable: `Artifactory` and `pipeline` -- OSUOSL LAN bandwidth??

### ISSUE THREAD

**Issue by aixtools** [adoptium/infrastructure#2461]
- Please put the system name in the title of this issue.
# Often AIX, but not solely
# OSUOSL is associated with both issues here - maybe that is the `outage` lack of network bandwidth (and why AIX systems are so frequently (ie, first) mentioned. See: #2455 

- Link to any log file showing the problem: (two recent cases)
- https://ci.adoptopenjdk.net/view/Test_grinder/job/Grinder/3367/console
- https://ci.adoptopenjdk.net/view/Test_grinder/job/Grinder/3365/console

- Please describe the issue:
Images such as: 
- `https://ci.adoptopenjdk.net/job/build-scripts/job/openjdk17-pipeline/284/artifact/target/aix/ppc64/hotspot/OpenJDK17U-jdk_ppc64_aix_hotspot_17.0.2_8.tar.gz`
- `https://openj9-artifactory.osuosl.org/artifactory/ci-openj9/Build_JDK11_x86-64_linux_Nightly/176/OpenJ9-JDK11-x86-64_linux-20211214-024449.tar.gz`

**Comment by sxa** [comment]
Is this issue different from #2455 or covering the same fundamental problem? Also it looks like both your grinder links are the same :-)

**Comment by aixtools** [comment]
- Thx. Fixed the grinder link.
- Same fundamental problem _BUT_ shows it is not specific to AIX. While I was typing, and saw the second URL was https:*.osuosl.org/... I began to think AIX was also suffering from an OSUOSL issue.

**Comment by sxa** [comment]
I'm still not sure I understand the issue here. The download in the second Grinder is pulling from the OpenJ9 artifactory instance but the transfer was successful and reached 100% based on the log. It did not fail. It looks like there was some issue with the contents of it, or the processing of it. I'm not sure that's related to data transfer. @llxia Is this a known issue?

```
20:52:34  /home/jenkins/workspace/Grinder/openjdkbinary/j2sdk-image/bin/java does not exist! Searching under TEST_JDK_HOME: /home/jenkins/workspace/Grinder/openjdkbinary/j2sdk-image...
20:52:34  find: '/home/jenkins/workspace/Grinder/openjdkbinary/j2sdk-image': No such file or directory
[Pipeline] }
```

**Comment by aixtools** [comment]
- I don't understand the ci-code either, but the 'fail' happens at the same point - and both situations are related to systems at osuosl.
- imho: the 'fail' is not related to the state of the `jenkins` process, but something they depend on, such as transfer speed/relability.
- if not too difficult, a potential change in the ci-code would be to do a 'retry' - if only for a short while (e.g., log somewhere what is being repeated) for an analysis over time.

**Comment by smlambert** [comment]
I believe the 2nd grinder is a user error, when using the unique and supported combination of SDK_RESOURCE=nightly and CUSTOMIZED_SDK_URL, the URL should not point to a tar.gz file.  If you point to a specific file or set of files rather than a directory, you must use SDK_RESOURCE=customized.  If you look at the fine print under CUSTOMIZED_SDK_URL, that gives examples of the URL for use in the case for 2nd grinder.  

I am fairly certain the ci code does retry... as similar issues have been seen in the OpenJ9 Jenkins and retries were added.

**Comment by aixtools** [comment]
ok. Then perhaps false positive, i.e., my assumption is baseless.

**Comment by sxa** [comment]
(Can re-open if it turns out to be a real separate problem from #2455)
