### ISSUE TITLE
Access request  ec2-54-78-186-5.eu-west-1.compute.amazonaws.com for sophia-guo

### ISSUE THREAD

**Issue by sophia-guo** [adoptium/infrastructure#2472]
Access level:

- [ ] root/Administrative

System for which access is needed:
regular update trss, which need root access.

**Comment by sxa** [comment]
I'm slightly reluctant to give out root access to a machine like this unless strictly necessary. I would like to have https://github.com/adoptium/infrastructure/issues/1327 understood and resolved to see if we can move this to not running as `root`. I heard rumours that it was due to the use of the `forever` service used to restart TRSS, but never saw any evidence of this (and I'm sure I've used `forever` in the past as non-root). Can we resolve that issue?

**Comment by sxa** [comment]
The desired activity (updating TRSS) [is now being done through jenkins](https://github.com/adoptium/infrastructure/issues/2598) - closing
