### ISSUE TITLE
Use JDK17 for the jenkins agent on macos/aarch64

### ISSUE THREAD

**Issue by sxa** [adoptium/infrastructure#2513]
It makes more sense to use a native JDK instead of relying on Rosetta to be able to run the jenkins agent. Since JDK17 is now GA and Temurin builds and releases it we should identify whether there would be any problems with using JDK17 as the JDK for running the jenkins agent.

(Ideally I'd prefer to run the test machines - as a minimum - WITHOUT Rosetta2 in order to ensure that we don't introduce dependencies on it, but it's a bit of a scalpel job to remove it once it's been installed)

**Comment by Haroon-Khel** [comment]
I've started https://ci.adoptopenjdk.net/computer/build-macstadium-macos11-arm64-1/log with a jdk-17 aarch64 binary. The grinder https://ci.adoptopenjdk.net/view/Test_grinder/job/Grinder/4688/console ran fine. 

Despite https://github.com/adoptium/infrastructure/issues/2533, this node hasn't crashed yet (though I used jdk16 in that issue so that error may be specific to jdk16)

I'll test a native jdk11 on one of the machines
