### ISSUE TITLE
Ansible request for GCC 11.2 for OpenJ9

### ISSUE THREAD

**Issue by AdamBrousseau** [adoptium/infrastructure#2538]
Please put the name of the software product (and affected platforms if relevant) in the title of this issue

- [ ] Missing install
- [ ] Bug in ansible playbook
- [x] Request for new playbook addition

Details:

We need GCC 11.2 added to the [centos 7 build image](https://hub.docker.com/r/adoptopenjdk/centos7_build_image) and therefore need it added to the Ansible Playbooks. This is to support building jdk19+. We need it in the containers for x64 and aarc64. For s390x and ppc64le we do machine installs.

**Comment by AdamBrousseau** [comment]
cc @vsebe

**Comment by sxa** [comment]
Can you clarify what you mean by "machine installs" on those?

**Comment by AdamBrousseau** [comment]
For p/z we run on the machines (not in containers) so we've already gone ahead and done those installs on our (Semeru) machines.

**Comment by sxa** [comment]
@AdamBrousseau Is the requirement for 11.2 specific to OpenJ9 because it's needed or because of a choice to use the latest based on the doc change at https://github.com/adoptium/jdk/commit/8384ac4ed3eaaa18998ab88e1ca36358c212e699? We recently moved up to 10.3 for many of our builds so we're at quite a 'good' level now (and one which supports all the options required for reproducible builds)

**Comment by AdamBrousseau** [comment]
[OpenJDK Build Platforms Doc](https://wiki.openjdk.java.net/display/Build/Supported+Build+Platforms) indicates that Oracle is bumping from 10.3 to 11.2 for jdk19. Dev had enough concerns about new features coming to recommend we keep up so we don't get bit. We are picking up the gcc10.3 change for 17 any day now but would also like to be prepared for 19+ by switching to gcc11.2. This also prepares us for jdk21-LTS next year which will be on at least gcc11.2.

**Comment by sxa** [comment]
Buiding with GCC 11.2 from 
`SHA256: d08edc536b54c372a1010ff6619dd274c0f1603aa49212ba20f7aa2cda36fa8b`
`SHA512: d53a0a966230895c54f01aea38696f818817b505f1e2bfa65e508753fcd01b2aedb4a61434f41f3a2ddbbd9f41384b96153c684ded3f0fa97c82758d9de5c7cf`

As before, building with the default compiler on CentOS7 except for x64 (CentOS6) and arm32 (Ubuntu 16.04) where I'm using /usr/local/gcc10/bin (`PATH`, `CC` and `CXX` all pointing in there, and `LD_LIBRARY_PATH` set to /usr/local/gcc10/lib*)

1. Extract tarball
2. contrib/download/prerequisites
3. ./configure --prefix=/usr/local/gcc11 --program-suffix=-11.3 (On x64 add `--disable-multilib`, on arm32 add `--with-float=hard`
4. make -j8 (Or whichever number is suitable for your system!)
5. make install
6. For x64, install [binutils 2.38](https://ftp.nluug.nl/pub/gnu/binutils/binutils-2.38.tar.xz) `sha256:e316477a914f567eccc34d5d29785b8b0f5a10208d36bbacedcc39048ecfe024` and [ccache 4.6.1](https://github.com/ccache/ccache/releases/download/v4.6.1/ccache-4.6.1.tar.xz) `sha256:e316477a914f567eccc34d5d29785b8b0f5a10208d36bbacedcc39048ecfe024` too (For binutils set `ln -s /bin/true /bin/makeinfo`, for ccache `-DZSTD_FROM_INTERNET=ON -DHIREDIS_FROM_INTERNET=ON`)
7. tar cJf gcc112.`uname -m`.tar.xz -C /usr/local gcc11

Timings:

Architecture | Parallel make | elapsed time | system time
--- | --- | --- | ---
x64 | -j50 | 18m30 | 222m03
aarch64 | -j160 | 28m30 | 242m40

Final SHA256sums:
- `0a48611fb83949513aff25070d17b3e3f65baf7b9f70681f601a0777794a8fdf  gcc112.x86_64.tar.xz`

**Comment by sxa** [comment]
I've also built with [GCC11.3.0](https://mirrorservice.org/sites/sourceware.org/pub/gcc/releases/gcc-11.3.0/gcc-11.3.0.tar.xz) SHA256: `b47cf2818691f5b1e21df2bb38c795fac2cfbd640ede2d0a5e1c89e338a3ac39` (with so we can can choose which of the two to use (Changes in 11.3 are [here](https://gcc.gnu.org/bugzilla/buglist.cgi?bug_status=RESOLVED&resolution=FIXED&target_milestone=11.3) This one included `--with-pkgversion="Adoptium/SXA 11.3.0"` so that our builds can be more easily identified int he `gcc --version` output:

Arch | time -j8 | system | xztime | SHA256sum
--- | --- | --- | --- | ---
x64 | 31m | | 12m25 | `a71458abf27097b3fc40d9d72dacda81c5a7b2adcb44b1e24032a1e1e4a53539`
aarch64 | 54m16 | 257m21 | 12m44 | `25214b9ecbd2d4b47b8a0ab5367262b4f0b176ee2f9db3aaeb29c74ae0fa2861`
s390x | 59m11 | 166m30 | 8m29 | `44e47d1f8a5f6878398070f635d043f0930d01f42abafe76c4ca9ff64ea35fcc`
ppc64le | 90m59 | 443m02 | 18m23 | `77a5a9be44189d9868fb66abd0a82967cc265bd3eeaa68095e2b298042cc9a82`
arm32 | 230m31 | 1161m52 | 24m36 | `6455a0865ddae47bfcee4d4b91f4a21fdba79a893bed682b54338c5a9d28779a`
