### ISSUE TITLE
Two jdk8 security tests consistently  failed on test-osuosl-centos74-ppc64le-1

### ISSUE THREAD

**Issue by sophia-guo** [adoptium/infrastructure#2625]
Recent builds run shows that JDK8 security tests:
sun/tools/jinfo/Basic.sh
sun/security/pkcs11/fips/TestTLS12.java

consistently failed on test-osuosl-centos74-ppc64le-1. 

- test suite/name? sun/tools/jinfo/Basic.sh   sun/security/pkcs11/fips/TestTLS12.java
- Is there an existing issue elsewhere covering this?
- Which machine(s) does it work on?  test-osuosl-ubuntu1804-ppc64le-1, test-osuosl-ubuntu1804-ppc64le-2, test-osuosl-ubuntu2004-ppc64le-1
- Which machine(s) does it fail on? test-osuosl-centos74-ppc64le-1
- Do you have a link to a Grinder re-run if the test with the failure? https://ci.adoptopenjdk.net/job/Grinder/parambuild/?SDK_RESOURCE=nightly&TARGET=jdk_custom&TEST_FLAG=&UPSTREAM_TEST_JOB_NAME=&DOCKER_REQUIRED=false&ACTIVE_NODE_TIMEOUT=&VENDOR_TEST_DIRS=&EXTRA_DOCKER_ARGS=-v+%24%7BTEST_JDK_HOME%7D%3A%2Fopt%2Fjava%2Fopenjdk&TKG_OWNER_BRANCH=AdoptOpenJDK%3Amaster&OPENJ9_SYSTEMTEST_OWNER_BRANCH=eclipse-openj9%3Amaster&PLATFORM=ppc64le_linux&GENERATE_JOBS=false&KEEP_REPORTDIR=true&PERSONAL_BUILD=true&ADOPTOPENJDK_REPO=https%3A%2F%2Fgithub.com%2Fadoptium%2Faqa-tests.git&LABEL=test-osuosl-centos74-ppc64le-1&EXTRA_OPTIONS=&CUSTOMIZED_SDK_URL=&BUILD_IDENTIFIER=&ADOPTOPENJDK_BRANCH=master&LIGHT_WEIGHT_CHECKOUT=false&NON_AQA_TEST_REPOS=&ARTIFACTORY_SERVER=&KEEP_WORKSPACE=false&USER_CREDENTIALS_ID=&JDK_VERSION=8&ITERATIONS=1&VENDOR_TEST_REPOS=&JDK_REPO=&OPENJ9_BRANCH=master&OPENJ9_SHA=&JCK_GIT_REPO=&VENDOR_TEST_BRANCHES=&OPENJ9_REPO=https%3A%2F%2Fgithub.com%2Feclipse%2Fopenj9.git&UPSTREAM_JOB_NAME=&CLOUD_PROVIDER=&PLATFORM_AND_MACHINE=&CUSTOM_TARGET=sun%2Fsecurity%2Fpkcs11%2Ffips%2FTestTLS12.java&VENDOR_TEST_SHAS=&JDK_BRANCH=&LABEL_ADDITION=&ARTIFACTORY_REPO=&ARTIFACTORY_ROOT_DIR=&UPSTREAM_TEST_JOB_NUMBER=&DOCKERIMAGE_TAG=&JDK_IMPL=hotspot&SSH_AGENT_CREDENTIAL=&AUTO_DETECT=true&DYNAMIC_COMPILE=false&ADOPTOPENJDK_SYSTEMTEST_OWNER_BRANCH=adoptium%3Amaster&CUSTOMIZED_SDK_URL_CREDENTIAL_ID=&OPENJDK_SHA=&NUM_MACHINES=&BUILD_LIST=openjdk&USE_TESTENV_PROPERTIES=false&UPSTREAM_JOB_NUMBER=&STF_OWNER_BRANCH=adoptium%3Amaster&TIME_LIMIT=10&JVM_OPTIONS=&PARALLEL=None
 
Any other details:
Grinder on test-osuosl-ubuntu1804-ppc64le-1: https://ci.adoptopenjdk.net/view/Test_grinder/job/Grinder/5017/, https://ci.adoptopenjdk.net/view/Test_grinder/job/Grinder/5016

Grinder on test-osuosl-centos74-ppc64le-1: https://ci.adoptopenjdk.net/view/Test_grinder/job/Grinder/5015, https://ci.adoptopenjdk.net/view/Test_grinder/job/Grinder/5014

**Comment by Haroon-Khel** [comment]
Rerunning on test-osuosl-centos74-ppc64le-1

sun/security/pkcs11/fips/TestTLS12.java
https://ci.adoptopenjdk.net/view/Test_grinder/job/Grinder/5092/console

sun/tools/jinfo/Basic.sh
https://ci.adoptopenjdk.net/view/Test_grinder/job/Grinder/5094/console

**Comment by Haroon-Khel** [comment]
Other ppc64 linux machines

sun/security/pkcs11/fips/TestTLS12.java

[test-osuosl-centos74-ppc64le-2](https://ci.adoptopenjdk.net/computer/test-osuosl-centos74-ppc64le-2/)
https://ci.adoptopenjdk.net/view/Test_grinder/job/Grinder/5095/console

https://ci.adoptopenjdk.net/view/Test_grinder/job/Grinder/5096/console
[test-osuosl-ubuntu1804-ppc64le-2](https://ci.adoptopenjdk.net/computer/test-osuosl-ubuntu1804-ppc64le-2/)

https://ci.adoptopenjdk.net/view/Test_grinder/job/Grinder/5097/console
[test-skytap-ubuntu2004-ppc64le-1](https://ci.adoptopenjdk.net/computer/test-skytap-ubuntu2004-ppc64le-1/)

https://ci.adoptopenjdk.net/view/Test_grinder/job/Grinder/5098/console
[test-osuosl-ubuntu1804-ppc64le-1](https://ci.adoptopenjdk.net/computer/test-osuosl-ubuntu1804-ppc64le-1/)

sun/tools/jinfo/Basic.sh

https://ci.adoptopenjdk.net/view/Test_grinder/job/Grinder/5100/console

https://ci.adoptopenjdk.net/view/Test_grinder/job/Grinder/5101/console

https://ci.adoptopenjdk.net/view/Test_grinder/job/Grinder/5102/console

https://ci.adoptopenjdk.net/view/Test_grinder/job/Grinder/5103/console

**Comment by Haroon-Khel** [comment]
Both tests also fail on [test-osuosl-centos74-ppc64le-2](https://ci.adoptopenjdk.net/computer/test-osuosl-centos74-ppc64le-2/)

**Comment by Haroon-Khel** [comment]
For the sun/tools/jinfo/Basic.sh failure, the following line causes the test to fail
https://github.com/adoptium/jdk8u/blob/a18e9043fa2a0a14098e1ec25d32577aaac6c023/jdk/test/sun/tools/jinfo/Basic.sh#L64

**Comment by Haroon-Khel** [comment]
Testing this in a command line environment on a failing machine, test-osuosl-centos74-ppc64le-1:

```
[jenkins@test-centos74-1 bin]$ ./jinfo -J-XX:+UsePerfData -flags +PrintGC 21443
Usage:
    jinfo <option> <pid>
       (to connect to a running process)

where <option> is one of:
    -flag <name>         to print the value of the named VM flag
    -flag [+|-]<name>    to enable or disable the named VM flag
    -flag <name>=<value> to set the named VM flag to the given value
    -h | -help           to print this help message
[jenkins@test-centos74-1 bin]$ ./jinfo -J-XX:+UsePerfData -sysprops 21443
Usage:
    jinfo <option> <pid>
       (to connect to a running process)

where <option> is one of:
    -flag <name>         to print the value of the named VM flag
    -flag [+|-]<name>    to enable or disable the named VM flag
    -flag <name>=<value> to set the named VM flag to the given value
    -h | -help           to print this help message
[jenkins@test-centos74-1 bin]$ ./jinfo -J-XX:+UsePerfData 21443
Usage:
    jinfo <option> <pid>
       (to connect to a running process)

where <option> is one of:
    -flag <name>         to print the value of the named VM flag
    -flag [+|-]<name>    to enable or disable the named VM flag
    -flag <name>=<value> to set the named VM flag to the given value
    -h | -help           to print this help message
```

While If I use one of the working options:

```
[jenkins@test-centos74-1 bin]$ ./jinfo -J-XX:+UsePerfData -flag -PrintGC 21443
[jenkins@test-centos74-1 bin]$ echo $?
0
```

**Comment by Haroon-Khel** [comment]
I think I've got it. These failing tests are not supposed to run on this machine. For example, on a passing machine, test-skytap-ubuntu2004-ppc64le-1, the `if` statement block which runs these failing tests does not run, https://github.com/adoptium/jdk8u/blob/a18e9043fa2a0a14098e1ec25d32577aaac6c023/jdk/test/sun/tools/jinfo/Basic.sh#L62, since the `$runSA = true` condition is false.

On test-skytap-ubuntu2004-ppc64le-1, the command `ptrace_scope=/sbin/sysctl -n kernel.yama.ptrace_scope`, from https://github.com/adoptium/jdk8u/blob/a18e9043fa2a0a14098e1ec25d32577aaac6c023/jdk/test/sun/tools/jinfo/Basic.sh#L54 returns `1` while on a failing machine, test-osuosl-centos74-ppc64le-1, it returns `0`

**Comment by Haroon-Khel** [comment]
Setting kernel.yama.ptrace_scope to 1 has fixed this

[jenkins@test-centos74-1 bin]$ /sbin/sysctl -n kernel.yama.ptrace_scope
1
[jenkins@test-centos74-1 bin]$ ./java -jar ../../jtreg/lib/jtreg.jar ../../jdk8u/jdk/test/sun/tools/jinfo/Basic.sh
Test results: passed: 1
Report written to /home/jenkins/jdk8u332-b09/bin/JTreport/html/report.html
Results written to /home/jenkins/jdk8u332-b09/bin/JTwork

**Comment by Haroon-Khel** [comment]
Rerunning sun/tools/jinfo/Basic.sh

centos-1
https://ci.adoptopenjdk.net/view/Test_grinder/job/Grinder/5170/console
centos-2
https://ci.adoptopenjdk.net/view/Test_grinder/job/Grinder/5171/console

**Comment by Haroon-Khel** [comment]
On a passing machine, the value for [sunPKCS11NSSProvider](https://github.com/adoptium/jdk8u/blob/a18e9043fa2a0a14098e1ec25d32577aaac6c023/jdk/test/sun/security/pkcs11/fips/TestTLS12.java#L417) is null, causing the test to skip. While on our 2 failing machines, this value is `SunPKCS11-NSSKeyStore version 1.8`

**Comment by Haroon-Khel** [comment]
Of the passing machines in https://github.com/adoptium/infrastructure/issues/2625#issuecomment-1176356298, the test skips

**Comment by Haroon-Khel** [comment]
The test skips on passing machine because https://github.com/adoptium/jdk8u/blob/3dca446d440e55cbb7dc3555392f4520ec9ff3bc/jdk/test/sun/security/pkcs11/SecmodTest.java#L45 returns false due to not being able to find `libsoftokn3.so`, while the failing centos machines have this library installed, and so the test will run on these machines and subsequently fail. 
However, on [test-skytap-ubuntu2004-ppc64le-1](https://ci.adoptopenjdk.net/computer/test-skytap-ubuntu2004-ppc64le-1/) I installed an `nsssoftoken` library into /usr/lib, yet the test still could not find the library and skipped the test

**Comment by steelhead31** [comment]
In order to get the test to pass on Centos7.4, this parameter is required -Djdk.tls.ephemeralDHKeySize=2048

**Comment by sxa** [comment]
Is this specific to ppc64le? That would seem quite strange if true. Also does the same fix allow the test to pass on Ubuntu systems?

**Comment by steelhead31** [comment]
The fix is specific to centos, on Ubuntu & Fedora, the test gets skipped...   
  
I've had this feedback from the OpenJDK team..  
  
_I think the permanent fix should go on the RHEL 9 build of OpenJDK, where_  
_we need to align with RH1974274 "java.txt file contains both security_  
_properties and system properties", now that System properties are in_  
_the /etc/crypto-policies/back-ends/javasystem.config file._  
  
_It seems Andrew Hughes is aware of this, by the conversations from the_  
_original RH1883312 ticket and the fedora-crypto-policies MR #104._  
  
_However, this is likely to have low priority in a tight backlog. Also,_  
_we need to re-think this in the context of the removal/reduction of_  
_downstream RHEL patches in OpenJDK packages with the goal shipping_  
_near-binary-identical builds to Temurin ones (OPENJDK-1199)._  
  
  
 _RH1974274:_ [_https://bugzilla.redhat.com/show_bug.cgi?id=1974274_](https://bugzilla.redhat.com/show_bug.cgi?id=1974274)  
 _RH1883312:_ [_https://bugzilla.redhat.com/show_bug.cgi?id=1883312_](https://bugzilla.redhat.com/show_bug.cgi?id=1883312)  
 _MR #104:_ [_https://gitlab.com/redhat-crypto/fedora-crypto-policies/-/merge_requests/104_](https://gitlab.com/redhat-crypto/fedora-crypto-policies/-/merge_requests/104OPENJDK-1199)  
[_OPENJDK-1199_](https://gitlab.com/redhat-crypto/fedora-crypto-policies/-/merge_requests/104OPENJDK-1199)_:_ [_https://issues.redhat.com/browse/OPENJDK-1199_](https://issues.redhat.com/browse/OPENJDK-1199)

**Comment by sxa** [comment]
> The fix is specific to centos, on Ubuntu & Fedora, the test gets skipped... 

Is that in `aqa-tests` or is it skipped in the openjdk codebase on those distros?

**Comment by steelhead31** [comment]
Yes, given that its skipped on Ubuntu & Fedora in aqa-tests,  is excluding the test on Linux/ppc64le an appropriate solution ?

**Comment by smlambert** [comment]
I think it is appropriate to exclude it [ProblemList_openjdk8.txt](https://github.com/adoptium/aqa-tests/blob/master/openjdk/excludes/ProblemList_openjdk8.txt) with reference to https://bugs.openjdk.org/browse/JDK-8029661 (or whichever bug notes that there is not an intention to fix in JDK8).

If only seen on ppc64le, is it because our CentOS nodes for x64 Linux are different version of CentOS or have different configuration?

**Comment by steelhead31** [comment]
After further discussions with @smlambert , and applying the required option would apply it too liberally to a number of tests, the decision has been made to exclude this test, so as to have the minimum impact. as this is deemed a low priority to fix upstream.

**Comment by sxa** [comment]
> If only seen on ppc64le, is it because our CentOS nodes for x64 Linux are different version of CentOS or have different configuration?

I've been wondering this too, although ppc64le is the only platform where we have active CentOS7 test systems as far as I can tell (https://ci.adoptium.net/manage/computer/test%2Daws%2Drhel76%2Darmv8%2D1/ exists but is currently not labelled for test - perhaps we could force a Grinder to it anyway to verify?)

We have a few CentOS/RHEL8 (e.g. https://ci.adoptium.net/manage/computer/test%2Ddocker%2Dcentos8%2Darmv8%2D1/) if we wanted to compare 7 vs 8 directly.

**Comment by steelhead31** [comment]
Tested on Centos 8 ( x64 & Arm64 ) without error, am just looking into whether it skips.

**Comment by sxa** [comment]
Suggest doing a test on the AWS aarch64 RHEL7 one too if possible.

**Comment by steelhead31** [comment]
In lieu of the upstream bug, this test has now been excluded in aqa PR ( adoptium/aqa-tests#4652 )

Excluding this test from JDK8. ( see [https://bugs.openjdk.org/browse/JDK-8029661](https://bugs.openjdk.org/browse/JDK-8029661) )
