### ISSUE TITLE
Tests jenkins jobs failed with `11:55:29  git clone -q git@github.com:adoptium/TKG.git 11:55:29  Host key verification failed` on arm32

### ISSUE THREAD

**Issue by sophia-guo** [adoptium/infrastructure#2683]
Tests jenkins jobs failed with `11:55:29  git clone -q git@github.com:adoptium/TKG.git 11:55:29  Host key verification failed` on arm32
https://ci.adoptopenjdk.net/job/Grinder/5307/console
https://ci.adoptopenjdk.net/job/Grinder/5302/
https://ci.adoptopenjdk.net/job/Grinder/5308/
https://ci.adoptopenjdk.net/job/Grinder/5309/

```
11:55:29  git clone -q git@github.com:adoptium/TKG.git
11:55:29  Host key verification failed.
11:55:29  fatal: Could not read from remote repository.
11:55:29  
11:55:29  Please make sure you have the correct access rights
11:55:29  and the repository exists.
11:55:29  error code: 128. Sleep 300 secs, then retry 1...
```

- test suite/name (e.g, BUILD_LIST, TARGET, CUSTOM_TARGET)? build stage to git clone TKG
- [a link into recent `Test_` job on https://ci.adoptopenjdk.net which showed the failure](https://ci.adoptopenjdk.net/job/Grinder/5307/console)
- Which machine(s) does it fail on? All available arm32 machines https://ci.adoptopenjdk.net/label/ci.role.test&&sw.os.linux&&hw.arch.aarch32/

Any other details:

**Comment by sophia-guo** [comment]
@sxa, could you take a look at this? All arm32 are affected

**Comment by sxa** [comment]
Those jobs have been run from a fork/branch which has [this change](https://github.com/sophia-guo/openjdk-tests/commit/53fb6f679b4a8b435e3ad1cd190e5f13fad2a258#diff-a6244f4c0516045b2cf1080cc973da3b4cb0443668d531e34befb21fc55f6a4e) in it which causes the clones of TKG etc. to be attempted over ssh instead of https. Switching it back to https will resolve this.
