### ISSUE TITLE
Alpine build nodes not dynamically provisioning, builds hanging

### ISSUE THREAD

**Issue by andrew-m-leonard** [adoptium/infrastructure#2988]
The nightly builds are hanging due to alpine platform failing to provision dynamic nodes: https://ci.adoptium.net/computer/azurebuildagentc16b00/

https://ci.adoptium.net/job/build-scripts/job/jobs/job/jdk17u/job/jdk17u-alpine-linux-x64-temurin/

**Comment by sxa** [comment]
I'm a bit confused as to why we're using the `alpine-linux` label for these builds. Since the alpine container can run on any Linux host capable of running the container `build&&linux&&x64&&dockerbuild` should be adequate and allow it to run on our other machines without the dependency on Azure - see https://ci.adoptium.net/job/build-scripts/job/jobs/job/jdk17u/job/jdk17u-alpine-linux-x64-temurin/185/ which is now chugging along quite nicely after I started it with different labels.

Regardless, I've deprovisioned the hanging agent so we'll see if it's repeatable.

**Comment by sxa** [comment]
While I'm loathed to do it I could stick the `alpine-linux` label onto the x64 dockerbuild systems, but it's not really accurate.

**Comment by sxa** [comment]
Hmmm `azurebuildagentc16b00` had apparently been running for 9 months.

**Comment by sxa** [comment]
OK We haven't had any dynamic provisions since the jenkins upgrade attempt yesterday by the look of it - we seem to have lost the Azure configuration.

**Comment by sxa** [comment]
I've reinstated the Azure configuration into the main `config.xml` of the jenkins server and reloaded it. It's now showing the cloud as active and provisioning at https://ci.adoptium.net/cloud-stats/

**Comment by sxa** [comment]
Not quite sure why it's felt the need to fire up seven of them simultaneously but 🤷🏻

**Comment by sxa** [comment]
Anyway, back up and running so I'll close this, although I would prefer us to change the labels.

**Comment by andrew-m-leonard** [comment]
To workaround the possiblility of alpine-linux jobs hanging builds indefinitely, the following node now as alpine-linux label on it:
```
dockerhost-equinix-ubuntu2204-x64-1
```

**Comment by sxa** [comment]
Let's be clear, that is a temporary workaround and as per [earlier comment](https://github.com/adoptium/infrastructure/issues/2988#issuecomment-1463717779) I don't want that machine labelled as `alpine-linux` as a permanent solution to this.

**Comment by sxa** [comment]
We can potentially look at having these run on the dynamic agents again now that the plugin has been rejuvinated. Putting in the plan so we can test.

**Comment by sxa** [comment]
One is running on a dynamic node just now: https://ci.adoptium.net/job/build-scripts/job/jobs/job/jdk23u/job/jdk23u-alpine-linux-x64-temurin/6/

**Comment by sxa** [comment]
Above build seems to have been successful - closing.
