### ISSUE TITLE
Issue With Centos7 Build Image Container on PPC64LE

### ISSUE THREAD

**Issue by steelhead31** [adoptium/infrastructure#3183]
The builds for JDK8, 11, 17, 20,etc are failing due to an issue with the adoptopenjdk/centos7\_build\_image, relevant details from the ongoing investigation are in the comments below, but also this slack thread..  
  
https://adoptium.slack.com/archives/C53GHCXL4/p1694004795268149

**Comment by steelhead31** [comment]
Currently the issues appears to be related to an (as yet) undetermined change in a docker image..

Image sha256:1718ad98c8a39dd7b6cdaac5fba56d4bc333d434ab3ad5eba148c3d5fbf4829c was created [here](https://ci.adoptium.net/view/Infra/job/centos7_docker_image_updater/362/console) and failed to build [here](https://ci.adoptium.net/job/build-scripts/job/jobs/job/jdk8u/job/jdk8u-linux-ppc64le-temurin/330/console).  
Image sha256:6a1880687647ec32430cdb6d2006d46e65fe3e1296e22753c8a7b5ec24816047 was created [here](https://ci.adoptium.net/view/Infra/job/centos7_docker_image_updater/359/consoleFull) and successfully built openjdk [here](https://ci.adoptium.net/job/build-scripts/job/jobs/job/jdk8u/job/jdk8u-linux-ppc64le-temurin/328/consoleFull).

**Comment by steelhead31** [comment]
images from #362 onwards are broken: [https://ci.adoptium.net/view/Infra/job/centos7_docker_image_updater/362/](https://ci.adoptium.net/view/Infra/job/centos7_docker_image_updater/362/)

**Comment by steelhead31** [comment]
Hmm I that could have activated a new kernel version and possible new container integration modules for the kernel ...  
Do we know the relative running of "new image being built" Vs "Restart of host that created it" Vs "When it started 

The reboot occurred (2nd Sept), then the image built(4th Sept), then the build failures ( although there was a successful 

Currently attempting to rebuild the docker image on the non-skytap node... also manually building the docker image on the skytap node..

So a rebuild of the image on a machine that hasnt been updated/rebooted also doesnt work....

**Comment by adamfarley** [comment]
Future docker image testing issue raised: https://github.com/adoptium/infrastructure/issues/3184

**Comment by andrew-m-leonard** [comment]
Some analysis running a container on skytap docker host, running image **sha256:40cdf0d6717ba7480cd6dd3f10e92f87feca1336356c8ce999910624fa501f22**:
```jenkins@dockerhost-skytap-ubuntu2004-ppc64le-1:~$ docker run -t -d -u 1000:1001 -e BUILDIMAGESHA=adoptopenjdk/centos7_build_image@sha256:40cdf0d6717ba7480cd6dd3f10e92f87feca1336356c8ce999910624fa501f22 -w /home/jenkins/workspace/build-scripts/jobs/jdk21/jdk21-linux-ppc64le-temurin -v /home/jenkins/workspace/build-scripts/jobs/jdk21/jdk21-linux-ppc64le-temurin:/home/jenkins/workspace/build-scripts/jobs/jdk21/jdk21-linux-ppc64le-temurin:rw,z -v /home/jenkins/workspace/build-scripts/jobs/jdk21/jdk21-linux-ppc64le-temurin@tmp:/home/jenkins/workspace/build-scripts/jobs/jdk21/jdk21-linux-ppc64le-temurin@tmp:rw,z  adoptopenjdk/centos7_build_image cat
3b3e8060b88f0f6e2dc6f2cbae94a68894f8c458dce38603206362e9d1a01259
jenkins@dockerhost-skytap-ubuntu2004-ppc64le-1:~$ 
jenkins@dockerhost-skytap-ubuntu2004-ppc64le-1:~$ docker exec -it 3b3e8060b88f0f6e2dc6f2cbae94a68894f8c458dce38603206362e9d1a01259 bash
bash: /home/jenkins/.bashrc: Permission denied
bash-4.2$ ls -l
total 84
-rw-rw-r-- 1 jenkins 1001  8596 Sep  4 13:41 CONTRIBUTING.md
-rw-rw-r-- 1 jenkins 1001  6142 Sep  4 13:41 FAQ.md
-rw-rw-r-- 1 jenkins 1001 11360 Sep  4 13:41 LICENSE
-rw-rw-r-- 1 jenkins 1001    65 Sep  4 13:41 NOTICE
-rw-rw-r-- 1 jenkins 1001 36695 Sep  4 13:41 README.md
drwxrwxr-x 3 jenkins 1001  4096 Sep  4 13:41 docs
drwxrwxr-x 6 jenkins 1001  4096 Sep  4 13:41 pipelines
drwxrwxr-x 4 jenkins 1001  4096 Sep 12 14:07 tools

**Comment by andrew-m-leonard** [comment]
Running with the last good image is slightly different **sha256:6a1880687647ec32430cdb6d2006d46e65fe3e1296e22753c8a7b5ec24816047**:
```
jenkins@dockerhost-skytap-ubuntu2004-ppc64le-1:~$ docker exec -it 74d3892bf7778acc4dd4cab814b863b772c0cd55e677c62e5ab601b17aa74120 bash
/usr/bin/id: cannot find name for group ID 1001
[jenkins@74d3892bf777 jdk21-linux-ppc64le-temurin]$ ls -l
total 84
-rw-rw-r-- 1 jenkins 1001  8596 Sep  4 13:41 CONTRIBUTING.md
-rw-rw-r-- 1 jenkins 1001  6142 Sep  4 13:41 FAQ.md
-rw-rw-r-- 1 jenkins 1001 11360 Sep  4 13:41 LICENSE
-rw-rw-r-- 1 jenkins 1001    65 Sep  4 13:41 NOTICE
-rw-rw-r-- 1 jenkins 1001 36695 Sep  4 13:41 README.md
drwxrwxr-x 3 jenkins 1001  4096 Sep  4 13:41 docs
drwxrwxr-x 6 jenkins 1001  4096 Sep  4 13:41 pipelines
drwxrwxr-x 4 jenkins 1001  4096 Sep 12 14:07 tools
```

**Comment by andrew-m-leonard** [comment]
@steelhead31 I think I may have worked out the pLinux build image issue, and it’s a matter of getting all the “ducks” line up!!
**Root problem:** skytap machine jenkins user has wrong groupid for the build image, needs to be 1000 so the permissions line up. Building the image on this node I think will generate a bad image due to the gid’s
**Secondary problems:**
When the updater job runs it pushed image: adoptopenjdk/centos7_build_image:linux-ppc64le
Then the last step of the updater job is “Push Docker Manifest”, this updates the dockerhub manifest so when you pull adoptopenjdk/centos7_build_image on a ppc64le box it actually pulls: adoptopenjdk/centos7_build_image:linux-ppc64le, and so-on for each platform. **BUT, if a single docker build fails, then the “Docker Manifest” stage does not run!** hence the platform manifest link is still pointing at the old image…. The Docker Manifest is not running most of the time, as typically either the build of armv7l or Alpine fails!

I’ve just confirmed this by disconnecting the skytap node, and running the centos7_docker_image_updater job, forcing the pLinux docker build on the good osusl node. The “docker manifest” failed as usual! So I submitted a build with: “DOCKER_IMAGE”: “adoptopenjdk/centos7_build_image:linux-ppc64le”,
and that is running successfully: https://ci.adoptium.net/job/build-scripts/job/jobs/job/jdk17u/job/jdk17u-linux-ppc64le-temurin/278/console

Actions:
1) Swap the skytap and jenkins user "gid" on the skytap host, so that jenkins is 1000:1000
2) Run the centos7_docker_image_updater repeating until all the builds are green and the "Docker Manifest" is updated. This will update adoptopenjdk/centos7_build_image to point at the good new image adoptopenjdk/centos7_build_image-ppc64le
3) Consider raising a new issue to allow an option on the centos7_docker_image_updater job, to choose which builds to run, so you can say update just one!

**Comment by steelhead31** [comment]
I've manually updated the groupids on the skytap server , and run a chmod across the jenkins homedirectory to change the GIDs in use..

**Comment by steelhead31** [comment]
This is now working, additional issues have been created for changes to testing etc #3184

**Comment by adamfarley** [comment]
Good job Scott! :)
