### ISSUE TITLE
Adoptium RHEL s390x nodes need strace installing

### ISSUE THREAD

**Issue by andrew-m-leonard** [adoptium/infrastructure#3451]
To support enabling SBOM strace, we need the Adoptium s390x RHEL nodes provisioned with strace

**Comment by sxa** [comment]
Because the process for rebuilding that image is "somewhat manual" I'm going to hold off on this until some other things, like the devkit evaluation on this architecture, is complete. If that is likely to cause a problem let me know. I know we've enabled it on other architectures so hopefully this will be ok :-)

**Comment by sxa** [comment]
This has been done as much as it can be and will be activated once we switch to using the new build images as [part of the devkit work](https://github.com/adoptium/temurin-build/issues/3700) on this platform...
No further work required here.
