### ISSUE TITLE
Ansible request for jq for test machines

### ISSUE THREAD

**Issue by sophia-guo** [adoptium/infrastructure#3453]
jq is need to install for reproducible comparing tests with sbom json file.

For windows with cygwin, cygwin need install jq

https://github.com/adoptium/temurin-build/issues/3687#issuecomment-1979626054

**Comment by sxa** [comment]
Based on discussions elsewhere I think the important thing will be to have this in the operating systems that we use on the [Linux test machines that can run docker](https://ci.adoptium.net/label/ci.role.test&&sw.tool.docker/) so that, plus Windows, should be the scope of this change.

Noting that `jq` does not exist in the repositories for CentOS7, so while there are CentOS74 and RHEL7 machines in that set, I am tempted to exclude them from this (maybe we should remove `sw.tool.docker` freom those hosts now?) since it would require installing from the repositories and since those OS versions are soon to be out of support I'm not sure there is benefit to doing that workaround. If anyone disagrees, please let me know.

**Comment by sxa** [comment]
Note: We may have to deploy `jq` under cygwin manually on the existing windows machines, as the change in the PR will only apply it to new installs of cygwin.

**Comment by sophia-guo** [comment]
Thanks @steelhead31 to deploy it manully on jenkins windows machines!
