### ISSUE TITLE
Failure to delete temp dir on build-ibmcloud-win2022-x64-1

### ISSUE THREAD

**Issue by sxa** [adoptium/infrastructure#3518]
Ref: https://ci.adoptium.net/job/build-scripts/job/jobs/job/release/job/jobs/job/jdk8u/job/jdk8u-release-windows-x64-temurin/16/console

```
18:20:46  ERROR: Failed to clean the workspace
18:20:46  jenkins.util.io.CompositeIOException: Unable to delete 'E:\Jenkins\workspace\temp'. Tried 3 times (of a maximum of 3) waiting 0.1 sec between attempts.
18:20:46  	at jenkins.util.io.PathRemover.forceRemoveDirectoryContents(PathRemover.java:87)
```

**Comment by steelhead31** [comment]
Having done some investigation, the e:\\workspace\\temp directory was being created with an unusual set of permissions, I've removed it manually, and recreated it... Im now running a build to try and determine if the build is corrupting the directory somehow, or if some other process is involved.

**Comment by steelhead31** [comment]
Test build running here: https://ci.adoptium.net/job/build-scripts/job/jobs/job/jdk8u/job/jdk8u-windows-x64-temurin/497/console

**Comment by steelhead31** [comment]
Having run 2 consecutive builds on the ibmcloud machine, without issues of it cleaning the workspace, Im inclined to switch the machine back online,  I assume a crash or other process, caused the permissions on that temp directory to be wrong(owned by administrator rather than jenkins), and removing the wrong one, and recreating with the correct permissions has resolved the issues in the build

**Comment by steelhead31** [comment]
Machine has been returned to service, following 2 x back to back builds without this problem recurring.
