### ISSUE TITLE
Commission 2 New VPC Hosts In Azure To Cover For IBM VPC Hosts

### ISSUE THREAD

**Issue by steelhead31** [adoptium/infrastructure#3589]
The current vagrant playbook check host is on Ubuntu 18.04. This requires a rebuild.

This is end of life, and requires an update. Ref: #3588

In order to maintain service, a replacement service is required to cover whilst the main VPC host is rebuilt.

**Comment by steelhead31** [comment]
Checking with @AdamBrousseau to see if a backup or snapshot of the machine is possible, as this is a large upgrade path, it may be problematic, and Im trying to not risk the machine. In the meantime I'll investigate the possibility of just upgrading ansible in the short term.

**Comment by sxa** [comment]
@steelhead31 @Haroon-Khel and I had a discussion on this today. Given the usefulness of the VPC functionality (and the fact there are some odd entries in the /etc/os-release which appears to show Debian instead of Ubuntu ncontnet) we have decided to avoid attempting to upgrade this server and to prototype a new Ubuntu 24.04 replacement on Azure with a view to using the knowledge gained from doing that to reinstall the existing vagrant server.

**Comment by steelhead31** [comment]
Following discussions last week, I've begun creating an azure based vagrant host as a proof of concept.
