### ISSUE TITLE
New machine request: Perf testing for jdk22 needs a mac

### ISSUE THREAD

**Issue by adamfarley** [adoptium/infrastructure#3652]
Issue: No Orka triggered with label [hw.arch.x86&&(sw.os.osx||sw.os.mac)&&ci.role.perf&&!sw.os.osx.10_14](https://ci.adoptium.net/label/hw.arch.x86&&%28sw.os.osx%7C%7Csw.os.mac%29&&ci.role.perf&&!sw.os.osx.10_14), which is required for perf jdk22.

[[hw.arch.x86&&(sw.os.osx||sw.os.mac)&&ci.role.perf&&!sw.os.osx.10_14](https://ci.adoptium.net/label/hw.arch.x86&&%28sw.os.osx%7C%7Csw.os.mac%29&&ci.role.perf&&!sw.os.osx.10_14)](https://github.com/adoptium/aqa-tests/issues/5235#issuecomment-2065614940)

Passed on 13th  and before on an orka system. No orka available for this release.

_Originally posted by @sophia-guo in https://github.com/adoptium/temurin/issues/28#issuecomment-2066667853_

**Comment by sxa** [comment]
https://ci.adoptium.net/job/Test_openjdk22_hs_sanity.perf_x86-64_mac/ still seems to be running ok - it looks like the orka machines are being provisioned appropriately.

(Using orka may be a bad idea since the machines are not necessarily consistent in terms of performance, but I don't see the blocker here for executing the performance tests just now)

**Comment by sxa** [comment]
@adamfarley @smlambert Do you think we have anything that needs to be fixed here in the short term? Is anything blocked or was this likely a transient problem?

**Comment by sxa** [comment]
Closing - can be re-opened if required.
