### ISSUE TITLE
Add trss-node to ci.adoptium.net

### ISSUE THREAD

**Issue by smlambert** [adoptium/infrastructure#3666]
We used to have the trss-node in the list of nodes on the public Jenkins server (https://ci.adoptium.net/computer/), so that we could do a regular code synch via a Jenkins job, https://ci.adoptium.net/view/Test_grinder/job/TRSS_Code_Sync/.  

That Jenkins job was disabled when we started running trss in a container on that machine (since the sync script would need to be updated with new commands).  Now that script is updated via https://github.com/adoptium/aqa-test-tools/pull/868, we would like to re-enable the job.

**Comment by steelhead31** [comment]
@smlambert I've created the node [https://ci.adoptium.net/computer/trss-node/](https://ci.adoptium.net/computer/trss-node/) in jenkins, and labelled it so that this job will pick it up [https://ci.adoptium.net/view/Test_grinder/job/TRSS_Code_Sync/](https://ci.adoptium.net/view/Test_grinder/job/TRSS_Code_Sync/) .   
  
Please check the value of the TRSS\_WORKSPACE parameter, for this job, which currently points to  .. /data/jenkins/aqa-test-tools , I suspect this will need updating.. ( the equivalent path appears to be /home/jenkins/trss/aqa-test-tools ).

**Comment by smlambert** [comment]
Thanks @steelhead31 !  I have updated TRSS_WORKSPACE in the job and also added ci.role.trss to the node configuration.  I will enable the schedule for this job after we are clear of the main tasks of the release.
