### ISSUE TITLE
EF request Signing Cert for SBOM Signing: https://gitlab.eclipse.org/eclipsefdn/helpdesk/-/issues/3835

### ISSUE THREAD

**Issue by smlambert** [adoptium/infrastructure#3803]
Converted from an entry in 2Q project plan

**Comment by sxa** [comment]
@smlambert Not quite sure what the 2Q entry was but this has already been acquired and is being tracked under [an epic in the build repo](https://github.com/adoptium/ci-jenkins-pipelines/issues/610), so not sure there is any work to be done under this issue. LMK if you think otherwise, or whether we can close it.

**Comment by smlambert** [comment]
This issue was still sitting open in the 2Q project plan (from which I have now mechanically transferred all open issues to the [Backlog](https://github.com/orgs/adoptium/projects/37) project and closed the [2Q](https://github.com/orgs/adoptium/projects/32) project).

If there is nothing to be done with this issue (I am not aware of any), then let's close it.
