### ISSUE TITLE
build-scaleway-ubuntu1604-armv7-[12] failing to deploy swapfile

### ISSUE THREAD

**Issue by sxa** [adoptium/infrastructure#462]
```
fatal: [build-scaleway-ubuntu1604-armv7-1]: FAILED! => {"changed": false, "cmd": "dphys-swapfile uninstall", "failed": true, "msg": "[Errno 2] No such file or directory", "rc": 2}
...ignoring
skipping: [test-softlayer-rhel74-x64-1]
fatal: [build-scaleway-ubuntu1604-armv7-2]: FAILED! => {"changed": false, "cmd": "dphys-swapfile uninstall", "failed": true, "msg": "[Errno 2] No such file or directory", "rc": 2}
```
https://ci.adoptopenjdk.net/computer/build-scaleway-armv7-ubuntu16-04-1/
https://ci.adoptopenjdk.net/computer/build-scaleway-armv7-ubuntu16-04-2/

**Comment by sxa555** [comment]
Here is the section of the playbook:
```
- name: Disable dphys-swapfile where applicable
  command: "dphys-swapfile uninstall"
  ignore_errors: yes
  when:
    - ansible_architecture == "armv7l"
  tags: swap_file
```
The machine does not have the `dphys-swapfile` command installed
This appears to come from the `dphys-swapfile` package and is designed to dynamically compute and set up a swapfile. The `uninstall` operation removes it, reclaiming the space. Since this has `ignore_errors: yes` we should be ok to leave this, but should probably either arrange for the package to be installed or stop trying to remove an existing swapfile. Unclear why this is only done on armv7l though.

**Comment by sxa555** [comment]
Not a critical failure (playbook still passes as `ok`) therefore removing from this milestone

**Comment by sxa** [comment]
Scaleway arm32 machines have been decomissioned - closing.
