### ISSUE TITLE
Decommission some JCK machines

### ISSUE THREAD

**Issue by tellison** [adoptium/infrastructure#610]
The JCK-specific machines are not being well utilized.

`jck-softlayer-x64-ubuntu-16.04-1`
`jck-softlayer-x64-ubuntu-16.04-2`
`jck-softlayer-x64-ubuntu-16.04-3`

Proposal is to decommission one or more at the moment.  Of course, they can always be recreated if required.

**Comment by sxa555** [comment]
I'm ok with this, but bear in mind that jck-softlayer-x64-ubuntu-16.04-3 is actually `jckservices.adoptopenjdk.net` so we should probably leave that one as it has the "external connectivity" services on it so if that goes the rest of them can't run it properly (although that's now fairly easy to regenerate if required too)

**Comment by tellison** [comment]
Ok, so I will now shutdown those machines, and also the remaining two Softlayer JCK machines
`jck-softlayer-x64-rhel-7.adoptopenjdk.net` and `jck-win2012-1.adoptopenjdk.net` as theya re not being used.

**Comment by gdams** [comment]
we should probably do the same with one of the s390x and one of the ppc64le machines too

**Comment by sxa555** [comment]
https://ci.adoptopenjdk.net/computer/test-macincloud-macos1010-3-XJ/ and https://ci.adoptopenjdk.net/computer/test-marist-ubuntu1604-s390x-2-XJ/ have been repurposed onto the main jenkins server - currently without any modifications. The s390x one will almost certainly fail to run variuos things without the playbooks being executed on it. The mac one we don't have playbooks fro so that may need manual work but it will be a good opportunity to catalogue what's needed specifically for a test system.

**Comment by sxa555** [comment]
Most of the important stuff has been moved, so chucking this on the backlog for now as it's not a priority.

Although arguably since this issues is titled with the word "some" we could just close it ;-)

**Comment by Willsparker** [comment]
As far as I can tell from the Inventory and Jenkins's node list, there aren't anymore `jck` nodes, and the node hosting `jckservices.adoptium.net` is running on an `azure-ubuntu2004` machine. Think this can be closed?

**Comment by sxa** [comment]
We still have them but they are hidden and running on a separate restricted jenkins server. The machines referenced here do not exist in the same form. Closing.
