### ISSUE TITLE
API playbook NPM install step failed to execute npm install

### ISSUE THREAD

**Issue by karianna** [adoptium/infrastructure#661]
Latest PR added octokit/rest but npm install failed to install this via the playbook and a manual npm install was required.

**Comment by sxa555** [comment]
Have never used this playbook before but will take a look

**Comment by sxa555** [comment]
Was that on the `NPM install api package.json` step - seemed to pass that step ok for me (It didn't run to completion though because `/usr/local/bin/forever` hadn't been created). Not sure why it isn't referencing it from `/usr/bin`.

Creating a link `/usr/local/bin/forever->/usr/bin/forever` appears to allow the operations to succeed (I stripped out the bits that use the jenkins user to avoid needing the keys etc). Do you have any more detail on the failure @karianna ?

**Comment by karianna** [comment]
We had a PR go in that added a new npm module (octokit/rest) when we ran the playbook it didn't run npm install and when it started (via forever) it naturally failed with a "Can't find octokit/rest" etc.  Hd to manually run npm install on the host.

**Comment by sxa** [comment]
@karianna This issue is over three years old and I can't remember what it was in relation to or where those actions are defined (IIRC we only use `forever` for TRSS. Can this be closed?
